package com.paylease.app.qa.testbase.dataproviders;

import static com.paylease.app.qa.framework.pages.paymentflow.PaymentMethodPage.NEW_BANK;
import static com.paylease.app.qa.framework.pages.paymentflow.PaymentMethodPage.NEW_CREDIT;
import static com.paylease.app.qa.framework.pages.paymentflow.PaymentMethodPage.NEW_DEBIT;
import static com.paylease.app.qa.functional.tests.integration.ResmanSplitTransactionTest.DEPOSIT_TRANS;
import static com.paylease.app.qa.functional.tests.integration.ResmanSplitTransactionTest.PAYMENT_TRANS;
import static com.paylease.app.qa.functional.tests.integration.ResmanSplitTransactionTest.REVERSAL_DEPOSIT_TRANS;
import static com.paylease.app.qa.functional.tests.integration.ResmanSplitTransactionTest.REVERSAL_PAYMENT_TRANS;

import org.testng.annotations.DataProvider;

public class ResmanSplitRefundDataProvider {

  /**
   * Data Provider for Resman Split Refunds.
   * @return parameters for Resman Split Refunds
   */
  @DataProvider(name = "resmanSplitRefund", parallel = true)
  public static Object[][] fullFlowRefund() {
    return new Object[][]{
        //-------------------------------------Refund from PM---------------------------------------
        {"tc01", "Refund Split 1 pay 1 dep Pm UI OTP from Res UI Bank",
            "fullFlowOnePaymentOneDeposit", NEW_BANK, "res",
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc02", "Refund Split 2 pay 2 dep Pm UI OTP from Res UI Bank",
            "fullFlowTwoPaymentTwoDeposit", NEW_BANK, "res",
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc03", "Refund Split 2 pay 1 dep Pm UI OTP from Res UI Bank",
            "fullFlowTwoPaymentOneDeposit", NEW_BANK, "res",
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc04", "Refund Split 1 pay 2 dep Pm UI OTP from Res UI Bank",
            "fullFlowOnePaymentTwoDeposit", NEW_BANK, "res",
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc05", "Refund Split 1 pay 0 dep Pm UI OTP from Res UI Bank", "fullFlowOnePayment",
            NEW_BANK, "res", new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS}},
        {"tc06", "Refund Split 0 pay 1 dep Pm UI OTP from Res UI Bank", "fullFlowOneDeposit",
            NEW_BANK, "res", new String[]{DEPOSIT_TRANS, REVERSAL_DEPOSIT_TRANS}},
        {"tc07", "Refund Split 2 pay 0 dep Pm UI OTP from Res UI Bank", "fullFlowTwoPayment",
            NEW_BANK, "res", new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS}},
        {"tc08", "Refund Split 0 pay 2 dep Pm UI OTP from Res UI Bank", "fullFlowTwoDeposit",
            NEW_BANK, "res", new String[]{DEPOSIT_TRANS, REVERSAL_DEPOSIT_TRANS}},
        {"tc09", "Refund Split 1 pay 1 dep Pm UI OTP from Res UI Credit",
            "fullFlowOnePaymentOneDeposit", NEW_CREDIT, "res",
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc10", "Refund Split 2 pay 2 dep Pm UI OTP from Res UI Credit",
            "fullFlowTwoPaymentTwoDeposit", NEW_CREDIT, "res",
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc11", "Refund Split 2 pay 1 dep Pm UI OTP from Res UI Credit",
            "fullFlowTwoPaymentOneDeposit", NEW_CREDIT, "res",
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc12", "Refund Split 1 pay 2 dep Pm UI OTP from Res UI Credit",
            "fullFlowOnePaymentTwoDeposit", NEW_CREDIT, "res",
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc13", "Refund Split 1 pay 0 dep Pm UI OTP from Res UI Credit", "fullFlowOnePayment",
            NEW_CREDIT, "res", new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS}},
        {"tc14", "Refund Split 0 pay 1 dep Pm UI OTP from Res UI Credit", "fullFlowOneDeposit",
            NEW_CREDIT, "res", new String[]{DEPOSIT_TRANS, REVERSAL_DEPOSIT_TRANS}},
        {"tc15", "Refund Split 2 pay 0 dep Pm UI OTP from Res UI Credit", "fullFlowTwoPayment",
            NEW_CREDIT, "res", new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS}},
        {"tc16", "Refund Split 0 pay 2 dep Pm UI OTP from Res UI Credit", "fullFlowTwoDeposit",
            NEW_CREDIT, "res", new String[]{DEPOSIT_TRANS, REVERSAL_DEPOSIT_TRANS}},
        {"tc17", "Refund Split 1 pay 1 dep Pm UI OTP from Res UI Debit",
            "fullFlowOnePaymentOneDeposit", NEW_DEBIT, "res",
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc18", "Refund Split 2 pay 2 dep Pm UI OTP from Res UI Debit",
            "fullFlowTwoPaymentTwoDeposit", NEW_DEBIT, "res",
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc19", "Refund Split 2 pay 1 dep Pm UI OTP from Res UI Debit",
            "fullFlowTwoPaymentOneDeposit", NEW_DEBIT, "res",
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc20", "Refund Split 1 pay 2 dep Pm UI OTP from Res UI Debit",
            "fullFlowOnePaymentTwoDeposit", NEW_DEBIT, "res",
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc21", "Refund Split 1 pay 0 dep Pm UI OTP from Res UI Debit", "fullFlowOnePayment",
            NEW_DEBIT, "res", new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS}},
        {"tc22", "Refund Split 0 pay 1 dep Pm UI OTP from Res UI Debit", "fullFlowOneDeposit",
            NEW_DEBIT, "res", new String[]{DEPOSIT_TRANS, REVERSAL_DEPOSIT_TRANS}},
        {"tc23", "Refund Split 2 pay 0 dep Pm UI OTP from Res UI Debit", "fullFlowTwoPayment",
            NEW_DEBIT, "res", new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS}},
        {"tc24", "Refund Split 0 pay 2 dep Pm UI OTP from Res UI Debit", "fullFlowTwoDeposit",
            NEW_DEBIT, "res", new String[]{DEPOSIT_TRANS, REVERSAL_DEPOSIT_TRANS}},

        {"tc25", "Refund Split 1 pay 1 dep Pm UI OTP from PM UI  Bank",
            "fullFlowOnePaymentOneDeposit", NEW_BANK, "pm",
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc26", "Refund Split 2 pay 2 dep Pm UI OTP from PM UI Bank",
            "fullFlowTwoPaymentTwoDeposit", NEW_BANK, "pm",
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc27", "Refund Split 2 pay 1 dep Pm UI OTP from PM UI Bank",
            "fullFlowTwoPaymentOneDeposit", NEW_BANK, "pm",
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc28", "Refund Split 1 pay 2 dep Pm UI OTP from PM UI Bank",
            "fullFlowOnePaymentTwoDeposit", NEW_BANK, "pm",
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc29", "Refund Split 1 pay 0 dep Pm UI OTP from PM UI Bank", "fullFlowOnePayment",
            NEW_BANK, "pm", new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS}},
        {"tc30", "Refund Split 0 pay 1 dep Pm UI OTP from PM UI Bank", "fullFlowOneDeposit",
            NEW_BANK, "pm", new String[]{DEPOSIT_TRANS, REVERSAL_DEPOSIT_TRANS}},
        {"tc31", "Refund Split 2 pay 0 dep Pm UI OTP from PM UI Bank", "fullFlowTwoPayment",
            NEW_BANK, "pm", new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS}},
        {"tc32", "Refund Split 0 pay 2 dep Pm UI OTP from PM UI Bank", "fullFlowTwoDeposit",
            NEW_BANK, "pm", new String[]{DEPOSIT_TRANS, REVERSAL_DEPOSIT_TRANS}},
        {"tc33", "Refund Split 1 pay 1 dep Pm UI OTP from PM UI Credit",
            "fullFlowOnePaymentOneDeposit", NEW_CREDIT, "pm",
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc34", "Refund Split 2 pay 2 dep Pm UI OTP from PM UI Credit",
            "fullFlowTwoPaymentTwoDeposit", NEW_CREDIT, "pm",
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc35", "Refund Split 2 pay 1 dep Pm UI OTP from PM UI Credit",
            "fullFlowTwoPaymentOneDeposit", NEW_CREDIT, "pm",
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc36", "Refund Split 1 pay 2 dep Pm UI OTP from PM UI Credit",
            "fullFlowOnePaymentTwoDeposit", NEW_CREDIT, "pm",
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc37", "Refund Split 1 pay 0 dep Pm UI OTP from PM UI Credit", "fullFlowOnePayment",
            NEW_CREDIT, "pm", new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS}},
        {"tc38", "Refund Split 0 pay 1 dep Pm UI OTP from PM UI Credit", "fullFlowOneDeposit",
            NEW_CREDIT, "pm", new String[]{DEPOSIT_TRANS, REVERSAL_DEPOSIT_TRANS}},
        {"tc39", "Refund Split 2 pay 0 dep Pm UI OTP from PM UI Credit", "fullFlowTwoPayment",
            NEW_CREDIT, "pm", new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS}},
        {"tc40", "Refund Split 0 pay 2 dep Pm UI OTP from PM UI Credit", "fullFlowTwoDeposit",
            NEW_CREDIT, "pm", new String[]{DEPOSIT_TRANS, REVERSAL_DEPOSIT_TRANS}},
        {"tc41", "Refund Split 1 pay 1 dep Pm UI OTP from PM UI Debit",
            "fullFlowOnePaymentOneDeposit", NEW_DEBIT, "pm",
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc42", "Refund Split 2 pay 2 dep Pm UI OTP from PM UI Debit",
            "fullFlowTwoPaymentTwoDeposit", NEW_DEBIT, "pm",
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc43", "Refund Split 2 pay 1 dep Pm UI OTP from PM UI Debit",
            "fullFlowTwoPaymentOneDeposit", NEW_DEBIT, "pm",
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc44", "Refund Split 1 pay 2 dep Pm UI OTP from PM UI Debit",
            "fullFlowOnePaymentTwoDeposit", NEW_DEBIT, "pm",
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc45", "Refund Split 1 pay 0 dep Pm UI OTP from PM UI Debit", "fullFlowOnePayment",
            NEW_DEBIT, "pm", new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS}},
        {"tc46", "Refund Split 0 pay 1 dep Pm UI OTP from PM UI Debit", "fullFlowOneDeposit",
            NEW_DEBIT, "pm", new String[]{DEPOSIT_TRANS, REVERSAL_DEPOSIT_TRANS}},
        {"tc47", "Refund Split 2 pay 0 dep Pm UI OTP from PM UI Debit", "fullFlowTwoPayment",
            NEW_DEBIT, "pm", new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS}},
        {"tc48", "Refund Split 0 pay 2 dep Pm UI OTP from PM UI Debit", "fullFlowTwoDeposit",
            NEW_DEBIT, "pm", new String[]{DEPOSIT_TRANS, REVERSAL_DEPOSIT_TRANS}}
    };
  }
}
