package com.paylease.app.qa.testbase.dataproviders;

import static com.paylease.app.qa.framework.pages.paymentflow.PaymentMethodPage.NEW_BANK;
import static com.paylease.app.qa.framework.pages.paymentflow.PaymentMethodPage.NEW_CREDIT;
import static com.paylease.app.qa.framework.pages.paymentflow.PaymentMethodPage.NEW_DEBIT;
import static com.paylease.app.qa.functional.tests.integration.ResmanSplitTransactionTest.DEPOSIT_TRANS;
import static com.paylease.app.qa.functional.tests.integration.ResmanSplitTransactionTest.PAYMENT_TRANS;
import static com.paylease.app.qa.functional.tests.integration.ResmanSplitTransactionTest.RETURN_DEPOSIT_TRANS;
import static com.paylease.app.qa.functional.tests.integration.ResmanSplitTransactionTest.RETURN_PAYMENT_TRANS;

import org.testng.annotations.DataProvider;

public class ResmanSplitVoidDataProvider {

  /**
   * Data Provider for Resman Split Voids.
   * @return the parameters for Resman Split Voids
   */
  @DataProvider(name = "resmanSplitVoid", parallel = true)
  public static Object[][] fullFlowVoid() {
    return new Object[][]{
        //---------------------------------Void from PM UI-----------------------------------------

        {"tc01", "Void From PM UI Split 1 pay 1 dep OTP from Res UI Bank",
            "fullFlowOnePaymentOneDeposit", NEW_BANK, "res", "pm",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc02", "Void From PM UI Split 2 pay 2 dep OTP from Res UI Bank",
            "fullFlowTwoPaymentTwoDeposit", NEW_BANK, "res", "pm",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc03", "Void From PM UI Split 2 pay 1 dep OTP from Res UI Bank",
            "fullFlowTwoPaymentOneDeposit", NEW_BANK, "res", "pm",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc04", "Void From PM UI Split 1 pay 2 dep OTP from Res UI Bank",
            "fullFlowOnePaymentTwoDeposit", NEW_BANK, "res", "pm",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc05", "Void From PM UI Split 1 pay 0 dep OTP from Res UI Bank", "fullFlowOnePayment",
            NEW_BANK, "res", "pm", new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS}},
        {"tc06", "Void From PM UI Split 0 pay 1 dep OTP from Res UI Bank", "fullFlowOneDeposit",
            NEW_BANK, "res", "pm", new String[]{DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc07", "Void From PM UI Split 2 pay 0 dep OTP from Res UI Bank", "fullFlowTwoPayment",
            NEW_BANK, "res", "pm", new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS}},
        {"tc08", "Void From PM UI Split 0 pay 2 dep OTP from Res UI Bank", "fullFlowTwoDeposit",
            NEW_BANK, "res", "pm", new String[]{DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc09", "Void From PM UI Split 1 pay 1 dep OTP from PM UI Bank",
            "fullFlowOnePaymentOneDeposit", NEW_BANK, "pm", "pm",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc10", "Void From PM UI Split 2 pay 2 dep OTP from PM UI Bank",
            "fullFlowTwoPaymentTwoDeposit", NEW_BANK, "pm", "pm",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc11", "Void From PM UI Split 2 pay 1 dep OTP from PM UI Bank",
            "fullFlowTwoPaymentOneDeposit", NEW_BANK, "pm", "pm",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc12", "Void From PM UI Split 1 pay 2 dep OTP from PM UI Bank",
            "fullFlowOnePaymentTwoDeposit", NEW_BANK, "pm", "pm",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc13", "Void From PM UI Split 1 pay 0 dep OTP from PM UI Bank", "fullFlowOnePayment",
            NEW_BANK, "pm", "pm", new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS}},
        {"tc14", "Void From PM UI Split 0 pay 1 dep OTP from PM UI Bank", "fullFlowOneDeposit",
            NEW_BANK, "pm", "pm", new String[]{DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc15", "Void From PM UI Split 2 pay 0 dep OTP from PM UI Bank", "fullFlowTwoPayment",
            NEW_BANK, "pm", "pm", new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS}},
        {"tc16", "Void From PM UI Split 0 pay 2 dep OTP from PM UI Bank", "fullFlowTwoDeposit",
            NEW_BANK, "pm", "pm", new String[]{DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},

        //-------------------------------------Void from Res UI-------------------------------------

        {"tc17", "Void From Res UI Split 1 pay 1 dep OTP from Res UI Bank",
            "fullFlowOnePaymentOneDeposit", NEW_BANK, "res", "res",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc18", "Void From Res UI Split 2 pay 2 dep OTP from Res UI Bank",
            "fullFlowTwoPaymentTwoDeposit", NEW_BANK, "res", "res",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc19", "Void From Res UI Split 2 pay 1 dep OTP from Res UI Bank",
            "fullFlowTwoPaymentOneDeposit", NEW_BANK, "res", "res",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc20", "Void From Res UI Split 1 pay 2 dep OTP from Res UI Bank",
            "fullFlowOnePaymentTwoDeposit", NEW_BANK, "res", "res",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc21", "Void From Res UI Split 1 pay 0 dep OTP from Res UI Bank", "fullFlowOnePayment",
            NEW_BANK, "res", "res", new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS}},
        {"tc22", "Void From Res UI Split 0 pay 1 dep OTP from Res UI Bank", "fullFlowOneDeposit",
            NEW_BANK, "res", "res", new String[]{DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc23", "Void From Res UI Split 2 pay 0 dep OTP from Res UI Bank", "fullFlowTwoPayment",
            NEW_BANK, "res", "res", new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS}},
        {"tc24", "Void From Res UI Split 0 pay 2 dep OTP from Res UI Bank", "fullFlowTwoDeposit",
            NEW_BANK, "res", "res", new String[]{DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc25", "Void From Res UI Split 1 pay 1 dep OTP from PM UI Bank",
            "fullFlowOnePaymentOneDeposit", NEW_BANK, "pm", "res",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc26", "Void From Res UI Split 2 pay 2 dep OTP from PM UI Bank",
            "fullFlowTwoPaymentTwoDeposit", NEW_BANK, "pm", "res",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc27", "Void From Res UI Split 2 pay 1 dep OTP from PM UI Bank",
            "fullFlowTwoPaymentOneDeposit", NEW_BANK, "pm", "res",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc28", "Void From Res UI Split 1 pay 2 dep OTP from PM UI Bank",
            "fullFlowOnePaymentTwoDeposit", NEW_BANK, "pm", "res",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc29", "Void From Res UI Split 1 pay 0 dep OTP from PM UI Bank", "fullFlowOnePayment",
            NEW_BANK, "pm", "res", new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS}},
        {"tc30", "Void From Res UI Split 0 pay 1 dep OTP from PM UI Bank", "fullFlowOneDeposit",
            NEW_BANK, "pm", "res", new String[]{DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc31", "Void From Res UI Split 2 pay 0 dep OTP from PM UI Bank", "fullFlowTwoPayment",
            NEW_BANK, "pm", "res", new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS}},
        {"tc32", "Void From Res UI Split 0 pay 2 dep OTP from PM UI Bank", "fullFlowTwoDeposit",
            NEW_BANK, "pm", "res", new String[]{DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},

        //------------------------------------Void from Admin---------------------------------------

        {"tc33", "Void From Admin UI Split 1 pay 1 dep OTP from Res UI Bank",
            "fullFlowOnePaymentOneDeposit", NEW_BANK, "res", "admin",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc34", "Void From Admin UI Split 2 pay 2 dep OTP from Res UI Bank",
            "fullFlowTwoPaymentTwoDeposit", NEW_BANK, "res", "admin",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc35", "Void From Admin UI Split 2 pay 1 dep OTP from Res UI Bank",
            "fullFlowTwoPaymentOneDeposit", NEW_BANK, "res", "admin",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc36", "Void From Admin UI Split 1 pay 2 dep OTP from Res UI Bank",
            "fullFlowOnePaymentTwoDeposit", NEW_BANK, "res", "admin",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc37", "Void From Admin UI Split 1 pay 0 dep OTP from Res UI Bank", "fullFlowOnePayment",
            NEW_BANK, "res", "admin", new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS}},
        {"tc38", "Void From Admin UI Split 0 pay 1 dep OTP from Res UI Bank", "fullFlowOneDeposit",
            NEW_BANK, "res", "admin", new String[]{DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc39", "Void From Admin UI Split 2 pay 0 dep OTP from Res UI Bank", "fullFlowTwoPayment",
            NEW_BANK, "res", "admin", new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS}},
        {"tc40", "Void From Admin UI Split 0 pay 2 dep OTP from Res UI Bank", "fullFlowTwoDeposit",
            NEW_BANK, "res", "admin", new String[]{DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc41", "Void From Admin UI Split 1 pay 1 dep OTP from Res UI Credit",
            "fullFlowOnePaymentOneDeposit", NEW_CREDIT, "res", "admin",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc42", "Void From Admin UI Split 2 pay 2 dep OTP from Res UI Credit",
            "fullFlowTwoPaymentTwoDeposit", NEW_CREDIT, "res", "admin",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc43", "Void From Admin UI Split 1 pay 2 dep OTP from Res UI Credit",
            "fullFlowOnePaymentTwoDeposit", NEW_CREDIT, "res", "admin",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc44", "Void From Admin UI Split 2 pay 1 dep OTP from Res UI Credit",
            "fullFlowTwoPaymentOneDeposit", NEW_CREDIT, "res", "admin",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc45", "Void From Admin UI Split 1 pay 0 dep OTP from Res UI Credit",
            "fullFlowOnePayment", NEW_CREDIT, "res", "admin",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS}},
        {"tc46", "Void From Admin UI Split 0 pay 1 dep OTP from Res UI Credit",
            "fullFlowOneDeposit", NEW_CREDIT, "res", "admin",
            new String[]{DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc47", "Void From Admin UI Split 2 pay 0 dep OTP from Res UI Credit",
            "fullFlowTwoPayment", NEW_CREDIT, "res", "admin",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS}},
        {"tc48", "Void From Admin UI Split 0 pay 2 dep OTP from Res UI Credit",
            "fullFlowTwoDeposit", NEW_CREDIT, "res", "admin",
            new String[]{DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc49", "Void From Admin UI Split 1 pay 1 dep OTP from Res UI Debit",
            "fullFlowOnePaymentOneDeposit", NEW_DEBIT, "res", "admin",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc50", "Void From Admin UI Split 2 pay 2 dep OTP from Res UI Debit",
            "fullFlowTwoPaymentTwoDeposit", NEW_DEBIT, "res", "admin",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc51", "Void From Admin UI Split 2 pay 1 dep OTP from Res UI Debit",
            "fullFlowTwoPaymentOneDeposit", NEW_DEBIT, "res", "admin",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc52", "Void From Admin UI Split 1 pay 2 dep OTP from Res UI Debit",
            "fullFlowOnePaymentTwoDeposit", NEW_DEBIT, "res", "admin",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc53", "Void From Admin UI Split 1 pay 0 dep OTP from Res UI Debit", "fullFlowOnePayment",
            NEW_DEBIT, "res", "admin", new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS}},
        {"tc54", "Void From Admin UI Split 0 pay 1 dep OTP from Res UI Debit", "fullFlowOneDeposit",
            NEW_DEBIT, "res", "admin", new String[]{DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc55", "Void From Admin UI Split 2 pay 0 dep OTP from Res UI Debit", "fullFlowTwoPayment",
            NEW_DEBIT, "res", "admin", new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS}},
        {"tc56", "Void From Admin UI Split 0 pay 2 dep OTP from Res UI Debit", "fullFlowTwoDeposit",
            NEW_DEBIT, "res", "admin", new String[]{DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc57", "Void From Admin UI Split 1 pay 1 dep OTP from PM UI Bank",
            "fullFlowOnePaymentOneDeposit", NEW_BANK, "pm", "admin",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc58", "Void From Admin UI Split 2 pay 2 dep OTP from PM UI Bank",
            "fullFlowTwoPaymentTwoDeposit", NEW_BANK, "pm", "admin",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc59", "Void From Admin UI Split 2 pay 1 dep OTP from PM UI Bank",
            "fullFlowTwoPaymentOneDeposit", NEW_BANK, "pm", "admin",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc60", "Void From Admin UI Split 1 pay 2 dep OTP from PM UI Bank",
            "fullFlowOnePaymentTwoDeposit", NEW_BANK, "pm", "admin",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc61", "Void From Admin UI Split 1 pay 0 dep OTP from PM UI Bank", "fullFlowOnePayment",
            NEW_BANK, "pm", "admin", new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS}},
        {"tc62", "Void From Admin UI Split 0 pay 1 dep OTP from PM UI Bank", "fullFlowOneDeposit",
            NEW_BANK, "pm", "admin", new String[]{DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc63", "Void From Admin UI Split 2 pay 0 dep OTP from PM UI Bank", "fullFlowTwoPayment",
            NEW_BANK, "pm", "admin", new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS}},
        {"tc64", "Void From Admin UI Split 0 pay 2 dep OTP from PM UI Bank", "fullFlowTwoDeposit",
            NEW_BANK, "pm", "admin", new String[]{DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc65", "Void From Admin UI Split 1 pay 1 dep OTP from PM UI Credit",
            "fullFlowOnePaymentOneDeposit", NEW_CREDIT, "pm", "admin",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc66", "Void From Admin UI Split 2 pay 2 dep OTP from PM UI Credit",
            "fullFlowTwoPaymentTwoDeposit", NEW_CREDIT, "pm", "admin",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc67", "Void From Admin UI Split 2 pay 1 dep OTP from PM UI Credit",
            "fullFlowTwoPaymentOneDeposit", NEW_CREDIT, "pm", "admin",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc68", "Void From Admin UI Split 1 pay 2 dep OTP from PM UI Credit",
            "fullFlowOnePaymentTwoDeposit", NEW_CREDIT, "pm", "admin",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc69", "Void From Admin UI Split 1 pay 0 dep OTP from PM UI Credit", "fullFlowOnePayment",
            NEW_CREDIT, "pm", "admin", new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS}},
        {"tc70", "Void From Admin UI Split 0 pay 1 dep OTP from PM UI Credit", "fullFlowOneDeposit",
            NEW_CREDIT, "pm", "admin", new String[]{DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc71", "Void From Admin UI Split 2 pay 0 dep OTP from PM UI Credit", "fullFlowTwoPayment",
            NEW_CREDIT, "pm", "admin", new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS}},
        {"tc72", "Void From Admin UI Split 0 pay 2 dep OTP from PM UI Credit", "fullFlowTwoDeposit",
            NEW_CREDIT, "pm", "admin", new String[]{DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc73", "Void From Admin UI Split 1 pay 1 dep OTP from PM UI Debit",
            "fullFlowOnePaymentOneDeposit", NEW_DEBIT, "pm", "admin",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc74", "Void From Admin UI Split 2 pay 2 dep OTP from PM UI Debit",
            "fullFlowTwoPaymentTwoDeposit", NEW_DEBIT, "pm", "admin",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc75", "Void From Admin UI Split 2 pay 1 dep OTP from PM UI Debit",
            "fullFlowTwoPaymentOneDeposit", NEW_DEBIT, "pm", "admin",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc76", "Void From Admin UI Split 1 pay 2 dep OTP from PM UI Debit",
            "fullFlowOnePaymentTwoDeposit", NEW_DEBIT, "pm", "admin",
            new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS, DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc77", "Void From Admin UI Split 1 pay 0 dep OTP from PM UI Debit", "fullFlowOnePayment",
            NEW_DEBIT, "pm", "admin", new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS}},
        {"tc78", "Void From Admin UI Split 0 pay 1 dep OTP from PM UI Debit", "fullFlowOneDeposit",
            NEW_DEBIT, "pm", "admin", new String[]{DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}},
        {"tc79", "Void From Admin UI Split 2 pay 0 dep OTP from PM UI Debit", "fullFlowTwoPayment",
            NEW_DEBIT, "pm", "admin", new String[]{PAYMENT_TRANS, RETURN_PAYMENT_TRANS}},
        {"tc80", "Void From Admin UI Split 0 pay 2 dep OTP from PM UI Debit", "fullFlowTwoDeposit",
            NEW_DEBIT, "pm", "admin", new String[]{DEPOSIT_TRANS, RETURN_DEPOSIT_TRANS}
        }
    };
  }
}
