package com.paylease.app.qa.testbase.dataproviders;

import static com.paylease.app.qa.framework.pages.paymentflow.PaymentMethodPage.NEW_BANK;
import static com.paylease.app.qa.framework.pages.paymentflow.PaymentMethodPage.NEW_CREDIT;
import static com.paylease.app.qa.framework.pages.paymentflow.PaymentMethodPage.NEW_DEBIT;
import static com.paylease.app.qa.functional.tests.integration.ResmanSplitTransactionTest.DEPOSIT_TRANS;
import static com.paylease.app.qa.functional.tests.integration.ResmanSplitTransactionTest.PAYMENT_TRANS;
import static com.paylease.app.qa.functional.tests.integration.ResmanSplitTransactionTest.REVERSAL_DEPOSIT_TRANS;
import static com.paylease.app.qa.functional.tests.integration.ResmanSplitTransactionTest.REVERSAL_PAYMENT_TRANS;

import org.testng.annotations.DataProvider;

public class ResmanSplitReversalDataProvider {

  /**
   * Data Provider for Resman Split Reversals.
   * @return parameters for Resman Split Reversals
   */
  @DataProvider(name = "resmanSplitReversal", parallel = true)
  public static Object[][] fullFlowReversal() {
    return new Object[][]{
        {"tc01", "Reversal Split 1 pay 1 dep OTP from PM UI BANK", "fullFlowOnePaymentOneDeposit",
            NEW_BANK, "pm", false,
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc02", "Reversal Split 2 pay 2 dep OTP from PM UI BANK", "fullFlowTwoPaymentTwoDeposit",
            NEW_BANK, "pm", false,
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc03", "Reversal Split 2 pay 1 dep OTP from PM UI BANK", "fullFlowTwoPaymentOneDeposit",
            NEW_BANK, "pm", false,
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc04", "Reversal Split 1 pay 2 dep OTP from PM UI BANK", "fullFlowOnePaymentTwoDeposit",
            NEW_BANK, "pm", false,
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc05", "Reversal Split 1 pay 0 dep OTP from PM UI BANK", "fullFlowOnePayment", NEW_BANK,
            "pm", false, new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS}},
        {"tc06", "Reversal Split 0 pay 1 dep OTP from PM UI BANK", "fullFlowOneDeposit", NEW_BANK,
            "pm", false, new String[]{DEPOSIT_TRANS, REVERSAL_DEPOSIT_TRANS}},
        {"tc07", "Reversal Split 2 pay 0 dep OTP from PM UI BANK", "fullFlowTwoPayment", NEW_BANK,
            "pm", false, new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS}},
        {"tc08", "Reversal Split 0 pay 2 dep OTP from PM UI BANK", "fullFlowTwoDeposit", NEW_BANK,
            "pm", false, new String[]{DEPOSIT_TRANS, REVERSAL_DEPOSIT_TRANS}},

        {"tc09", "Reversal Split 1 pay 1 dep OTP from PM UI Credit", "fullFlowOnePaymentOneDeposit",
            NEW_CREDIT, "pm", false,
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc10", "Reversal Split 2 pay 2 dep OTP from PM UI Credit", "fullFlowTwoPaymentTwoDeposit",
            NEW_CREDIT, "pm", false,
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc11", "Reversal Split 2 pay 1 dep OTP from PM UI Credit", "fullFlowTwoPaymentOneDeposit",
            NEW_CREDIT, "pm", false,
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc12", "Reversal Split 1 pay 2 dep OTP from PM UI Credit", "fullFlowOnePaymentTwoDeposit",
            NEW_CREDIT, "pm", false,
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc13", "Reversal Split 1 pay 0 dep OTP from PM UI Credit", "fullFlowOnePayment",
            NEW_CREDIT, "pm", false, new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS}},
        {"tc14", "Reversal Split 0 pay 1 dep OTP from PM UI Credit", "fullFlowOneDeposit",
            NEW_CREDIT, "pm", false, new String[]{DEPOSIT_TRANS, REVERSAL_DEPOSIT_TRANS}},
        {"tc15", "Reversal Split 2 pay 0 dep OTP from PM UI Credit", "fullFlowTwoPayment",
            NEW_CREDIT, "pm", false, new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS}},
        {"tc16", "Reversal Split 0 pay 2 dep OTP from PM UI Credit", "fullFlowTwoDeposit",
            NEW_CREDIT, "pm", false, new String[]{DEPOSIT_TRANS, REVERSAL_DEPOSIT_TRANS}},

        {"tc17", "Reversal Split 1 pay 1 dep OTP from PM UI Debit", "fullFlowOnePaymentOneDeposit",
            NEW_DEBIT, "pm", false,
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc18", "Reversal Split 2 pay 2 dep OTP from PM UI Debit", "fullFlowTwoPaymentTwoDeposit",
            NEW_DEBIT, "pm", false,
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc19", "Reversal Split 2 pay 1 dep OTP from PM UI Debit", "fullFlowTwoPaymentOneDeposit",
            NEW_DEBIT, "pm", false,
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc20", "Reversal Split 1 pay 2 dep OTP from PM UI Debit", "fullFlowOnePaymentTwoDeposit",
            NEW_DEBIT, "pm", false,
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc21", "Reversal Split 1 pay 0 dep OTP from PM UI Debit", "fullFlowOnePayment", NEW_DEBIT,
            "pm", false, new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS}},
        {"tc22", "Reversal Split 0 pay 1 dep OTP from PM UI Debit", "fullFlowOneDeposit", NEW_DEBIT,
            "pm", false, new String[]{DEPOSIT_TRANS, REVERSAL_DEPOSIT_TRANS}},
        {"tc23", "Reversal Split 2 pay 0 dep OTP from PM UI Debit", "fullFlowTwoPayment", NEW_DEBIT,
            "pm", false, new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS}},
        {"tc24", "Reversal Split 0 pay 2 dep OTP from PM UI Debit", "fullFlowTwoDeposit", NEW_DEBIT,
            "pm", false, new String[]{DEPOSIT_TRANS, REVERSAL_DEPOSIT_TRANS}},

        {"tc25", "Reversal Split 1 pay 1 dep OTP from RES UI Bank", "fullFlowOnePaymentOneDeposit",
            NEW_BANK, "res", false,
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc26", "Reversal Split 2 pay 2 dep OTP from RES UI Bank", "fullFlowTwoPaymentTwoDeposit",
            NEW_BANK, "res", false,
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc27", "Reversal Split 2 pay 1 dep OTP from RES UI Bank", "fullFlowTwoPaymentOneDeposit",
            NEW_BANK, "res", false,
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc28", "Reversal Split 1 pay 2 dep OTP from RES UI Bank", "fullFlowOnePaymentTwoDeposit",
            NEW_BANK, "res", false,
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc29", "Reversal Split 1 pay 0 dep OTP from RES UI Bank", "fullFlowOnePayment", NEW_BANK,
            "res", false, new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS}},
        {"tc30", "Reversal Split 0 pay 1 dep OTP from RES UI Bank", "fullFlowOneDeposit", NEW_BANK,
            "res", false, new String[]{DEPOSIT_TRANS, REVERSAL_DEPOSIT_TRANS}},
        {"tc31", "Reversal Split 2 pay 0 dep OTP from RES UI Bank", "fullFlowTwoPayment", NEW_BANK,
            "res", false, new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS}},
        {"tc32", "Reversal Split 0 pay 2 dep OTP from RES UI Bank", "fullFlowTwoDeposit", NEW_BANK,
            "res", false, new String[]{DEPOSIT_TRANS, REVERSAL_DEPOSIT_TRANS}},

        {"tc33", "Reversal Split 1 pay 1 dep OTP from RES UI Credit",
            "fullFlowOnePaymentOneDeposit", NEW_CREDIT, "res", false,
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc34", "Reversal Split 2 pay 2 dep OTP from RES UI Credit",
            "fullFlowTwoPaymentTwoDeposit", NEW_CREDIT, "res", false,
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc35", "Reversal Split 2 pay 1 dep OTP from RES UI Credit",
            "fullFlowTwoPaymentOneDeposit", NEW_CREDIT, "res", false,
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc36", "Reversal Split 1 pay 2 dep OTP from RES UI Credit",
            "fullFlowOnePaymentTwoDeposit", NEW_CREDIT, "res", false,
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc37", "Reversal Split 1 pay 0 dep OTP from RES UI Credit", "fullFlowOnePayment",
            NEW_CREDIT, "res", true, new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS}},
        {"tc38", "Reversal Split 0 pay 1 dep OTP from RES UI Credit", "fullFlowOneDeposit",
            NEW_CREDIT, "res", false, new String[]{DEPOSIT_TRANS, REVERSAL_DEPOSIT_TRANS}},
        {"tc39", "Reversal Split 2 pay 0 dep OTP from RES UI Credit", "fullFlowTwoPayment",
            NEW_CREDIT, "res", false, new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS}},
        {"tc40", "Reversal Split 0 pay 2 dep OTP from RES UI Credit", "fullFlowTwoDeposit",
            NEW_CREDIT, "res", false, new String[]{DEPOSIT_TRANS, REVERSAL_DEPOSIT_TRANS}},

        {"tc41", "Reversal Split 1 pay 1 dep OTP from RES UI Debit", "fullFlowOnePaymentOneDeposit",
            NEW_DEBIT, "res", false,
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc42", "Reversal Split 2 pay 2 dep OTP from RES UI Debit", "fullFlowTwoPaymentTwoDeposit",
            NEW_DEBIT, "res", false,
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc43", "Reversal Split 2 pay 1 dep OTP from RES UI Debit", "fullFlowTwoPaymentOneDeposit",
            NEW_DEBIT, "res", false,
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc44", "Reversal Split 1 pay 2 dep OTP from RES UI Debit", "fullFlowOnePaymentTwoDeposit",
            NEW_DEBIT, "res", false,
            new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS, DEPOSIT_TRANS,
                REVERSAL_DEPOSIT_TRANS}},
        {"tc45", "Reversal Split 1 pay 0 dep OTP from RES UI Debit", "fullFlowOnePayment",
            NEW_DEBIT, "res", false, new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS}},
        {"tc46", "Reversal Split 0 pay 1 dep OTP from RES UI Debit", "fullFlowOneDeposit",
            NEW_DEBIT, "res", false, new String[]{DEPOSIT_TRANS, REVERSAL_DEPOSIT_TRANS}},
        {"tc47", "Reversal Split 2 pay 0 dep OTP from RES UI Debit", "fullFlowTwoPayment",
            NEW_DEBIT, "res", false, new String[]{PAYMENT_TRANS, REVERSAL_PAYMENT_TRANS}},
        {"tc48", "Reversal Split 0 pay 2 dep OTP from RES UI Debit", "fullFlowTwoDeposit",
            NEW_DEBIT, "res", false, new String[]{DEPOSIT_TRANS, REVERSAL_DEPOSIT_TRANS}},

        {"tc49", "Partial Reversal Split 1 pay 1 dep OTP from PM UI Bank",
            "fullFlowOnePaymentOneDeposit", NEW_BANK, "pm", true,
            new String[]{PAYMENT_TRANS, DEPOSIT_TRANS}},
        {"tc50", "Partial Reversal Split 2 pay 2 dep OTP from PM UI Bank",
            "fullFlowTwoPaymentTwoDeposit", NEW_BANK, "pm", true,
            new String[]{PAYMENT_TRANS, DEPOSIT_TRANS}},
        {"tc51", "Partial Reversal Split 2 pay 1 dep OTP from PM UI Bank",
            "fullFlowTwoPaymentOneDeposit", NEW_BANK, "pm", true,
            new String[]{PAYMENT_TRANS, DEPOSIT_TRANS}},
        {"tc52", "Partial Reversal Split 1 pay 2 dep OTP from PM UI Bank",
            "fullFlowOnePaymentTwoDeposit", NEW_BANK, "pm", true,
            new String[]{PAYMENT_TRANS, DEPOSIT_TRANS}},
        {"tc53", "Partial Reversal Split 2 pay 0 dep OTP from PM UI Bank", "fullFlowTwoPayment",
            NEW_BANK, "pm", true, new String[]{PAYMENT_TRANS}},
        {"tc54", "Partial Reversal Split 0 pay 2 dep OTP from PM UI Bank", "fullFlowTwoDeposit",
            NEW_BANK, "pm", true, new String[]{DEPOSIT_TRANS}},

        {"tc55", "Partial Reversal Split 1 pay 1 dep OTP from PM UI Credit",
            "fullFlowOnePaymentOneDeposit", NEW_CREDIT, "pm", true,
            new String[]{PAYMENT_TRANS, DEPOSIT_TRANS}},
        {"tc56", "Partial Reversal Split 2 pay 2 dep OTP from PM UI Credit",
            "fullFlowTwoPaymentTwoDeposit", NEW_CREDIT, "pm", true,
            new String[]{PAYMENT_TRANS, DEPOSIT_TRANS}},
        {"tc57", "Partial Reversal Split 2 pay 1 dep OTP from PM UI Credit",
            "fullFlowTwoPaymentOneDeposit", NEW_CREDIT, "pm", true,
            new String[]{PAYMENT_TRANS, DEPOSIT_TRANS}},
        {"tc58", "Partial Reversal Split 1 pay 2 dep OTP from PM UI Credit",
            "fullFlowOnePaymentTwoDeposit", NEW_CREDIT, "pm", true,
            new String[]{PAYMENT_TRANS, DEPOSIT_TRANS}},
        {"tc59", "Partial Reversal Split 2 pay 0 dep OTP from PM UI Credit", "fullFlowTwoPayment",
            NEW_CREDIT, "pm", true, new String[]{PAYMENT_TRANS}},
        {"tc60", "Partial Reversal Split 0 pay 2 dep OTP from PM UI Credit", "fullFlowTwoDeposit",
            NEW_CREDIT, "pm", true, new String[]{DEPOSIT_TRANS}},

        {"tc61", "Partial Reversal Split 1 pay 1 dep OTP from PM UI Debit",
            "fullFlowOnePaymentOneDeposit", NEW_DEBIT, "pm", true,
            new String[]{PAYMENT_TRANS, DEPOSIT_TRANS}},
        {"tc62", "Partial Reversal Split 2 pay 2 dep OTP from PM UI Debit",
            "fullFlowTwoPaymentTwoDeposit", NEW_DEBIT, "pm", true,
            new String[]{PAYMENT_TRANS, DEPOSIT_TRANS}},
        {"tc63", "Partial Reversal Split 2 pay 1 dep OTP from PM UI Debit",
            "fullFlowTwoPaymentOneDeposit", NEW_DEBIT, "pm", true,
            new String[]{PAYMENT_TRANS, DEPOSIT_TRANS}},
        {"tc64", "Partial Reversal Split 1 pay 2 dep OTP from PM UI Debit",
            "fullFlowOnePaymentTwoDeposit", NEW_DEBIT, "pm", true,
            new String[]{PAYMENT_TRANS, DEPOSIT_TRANS}},
        {"tc65", "Partial Reversal Split 2 pay 0 dep OTP from PM UI Debit", "fullFlowTwoPayment",
            NEW_DEBIT, "pm", true, new String[]{PAYMENT_TRANS}},
        {"tc66", "Partial Reversal Split 0 pay 2 dep OTP from PM UI Debit", "fullFlowTwoDeposit",
            NEW_DEBIT, "pm", true, new String[]{DEPOSIT_TRANS}},

        {"tc67", "Partial Reversal Split 1 pay 1 dep OTP from Res UI Bank",
            "fullFlowOnePaymentOneDeposit", NEW_BANK, "res", true,
            new String[]{PAYMENT_TRANS, DEPOSIT_TRANS}},
        {"tc68", "Partial Reversal Split 2 pay 2 dep OTP from Res UI Bank",
            "fullFlowTwoPaymentTwoDeposit", NEW_BANK, "res", true,
            new String[]{PAYMENT_TRANS, DEPOSIT_TRANS}},
        {"tc69", "Partial Reversal Split 2 pay 1 dep OTP from Res UI Bank",
            "fullFlowTwoPaymentOneDeposit", NEW_BANK, "res", true,
            new String[]{PAYMENT_TRANS, DEPOSIT_TRANS}},
        {"tc70", "Partial Reversal Split 1 pay 2 dep OTP from Res UI Bank",
            "fullFlowOnePaymentTwoDeposit", NEW_BANK, "res", true,
            new String[]{PAYMENT_TRANS, DEPOSIT_TRANS}},
        {"tc71", "Partial Reversal Split 2 pay 0 dep OTP from Res UI Bank", "fullFlowTwoPayment",
            NEW_BANK, "res", true, new String[]{PAYMENT_TRANS}},
        {"tc72", "Partial Reversal Split 0 pay 2 dep OTP from Res UI Bank", "fullFlowTwoDeposit",
            NEW_BANK, "res", true, new String[]{DEPOSIT_TRANS}},

        {"tc73", "Partial Reversal Split 1 pay 1 dep OTP from Res UI Credit",
            "fullFlowOnePaymentOneDeposit", NEW_CREDIT, "res", true,
            new String[]{PAYMENT_TRANS, DEPOSIT_TRANS}},
        {"tc74", "Partial Reversal Split 2 pay 2 dep OTP from Res UI Credit",
            "fullFlowTwoPaymentTwoDeposit", NEW_CREDIT, "res", true,
            new String[]{PAYMENT_TRANS, DEPOSIT_TRANS}},
        {"tc75", "Partial Reversal Split 2 pay 1 dep OTP from Res UI Credit",
            "fullFlowTwoPaymentOneDeposit", NEW_CREDIT, "res", true,
            new String[]{PAYMENT_TRANS, DEPOSIT_TRANS}},
        {"tc76", "Partial Reversal Split 1 pay 2 dep OTP from Res UI Credit",
            "fullFlowOnePaymentTwoDeposit", NEW_CREDIT, "res", true,
            new String[]{PAYMENT_TRANS, DEPOSIT_TRANS}},
        {"tc77", "Partial Reversal Split 2 pay 0 dep OTP from Res UI Credit", "fullFlowTwoPayment",
            NEW_CREDIT, "res", true, new String[]{PAYMENT_TRANS}},
        {"tc78", "Partial Reversal Split 0 pay 2 dep OTP from Res UI Credit", "fullFlowTwoDeposit",
            NEW_CREDIT, "res", true, new String[]{DEPOSIT_TRANS}},

        {"tc79", "Partial Reversal Split 1 pay 1 dep OTP from Res UI Debit",
            "fullFlowOnePaymentOneDeposit", NEW_DEBIT, "res", true,
            new String[]{PAYMENT_TRANS, DEPOSIT_TRANS}},
        {"tc80", "Partial Reversal Split 2 pay 2 dep OTP from Res UI Debit",
            "fullFlowTwoPaymentTwoDeposit", NEW_DEBIT, "res", true,
            new String[]{PAYMENT_TRANS, DEPOSIT_TRANS}},
        {"tc81", "Partial Reversal Split 2 pay 1 dep OTP from Res UI Debit",
            "fullFlowTwoPaymentOneDeposit", NEW_DEBIT, "res", true,
            new String[]{PAYMENT_TRANS, DEPOSIT_TRANS}},
        {"tc82", "Partial Reversal Split 1 pay 2 dep OTP from Res UI Debit",
            "fullFlowOnePaymentTwoDeposit", NEW_DEBIT, "res", true,
            new String[]{PAYMENT_TRANS, DEPOSIT_TRANS}},
        {"tc83", "Partial Reversal Split 2 pay 0 dep OTP from Res UI Debit", "fullFlowTwoPayment",
            NEW_DEBIT, "res", true, new String[]{PAYMENT_TRANS}},
        {"tc84", "Partial Reversal Split 0 pay 2 dep OTP from Res UI Debit", "fullFlowTwoDeposit",
            NEW_DEBIT, "res", true, new String[]{DEPOSIT_TRANS}}
    };
  }
}
